id: main
title: "&0&lКлановое меню"
size: 54
open_permission: none
open_commands:
  - "tessst"

test: "sex"

Items:

  info:
    material: DIAMOND_SWORD
    slot: 49
    hide_attributes: true
    display_name: "&6Клан %clan_prefix% &8(%clan_tag%)"
    lore:
      - "&6• &fЛидер: &6&l%clan_leader_name%"
      - "&6• &fБаланс: &6&l%clan_balance%"
      - "&6• &fОпыт: &6&l%clan_exp%&7/&c&l%clan_exp_max%"
      - "&6• &fУровень: &6&l%clan_level%"

  orange:
    material: ORANGE_STAINED_GLASS_PANE
    slot:
      - 0-2
      - 6-8
      - 45-47
      - 51-53
    display_name: " "

  black:
    material: BLACK_STAINED_GLASS_PANE
    slot:
      - 3
      - 5
      - 48
      - 50
    display_name: " "


  gray:
    material: GRAY_STAINED_GLASS_PANE
    slot: 4
    display_name: " "




